services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=attendancetracker
    ports:
      - "5432:5432"

  attendancetracker-backend:
    container_name: attendancetracker-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - AT_URL=jdbc:postgresql://psql-db:5432/attendancetracker
      - AT_USERNAME=admin
      - AT_PASSWORD=1234
      - AT_CORS=http://localhost:5173
    depends_on:
      - psql-db
